## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Mentor Graphics Corporation
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

USES_DPI = 1
ifdef UVM_NO_DPI
  USES_DPI=0
endif

#---------------------------------------------------------------
# Define Variables
#---------------------------------------------------------------

UVM_HOME ?= ../..


LIBDIR  = $(UVM_HOME)/lib
#GCC     = $(MTI_HOME)/gcc-4.1.2-linux/bin/g++
GCC     = gcc
TEST    = /usr/bin/test
BITS    ?= 32
LIBNAME = uvm_dpi
DPI_SRC = $(UVM_HOME)/src/dpi/uvm_dpi.cc


GCCCMD =  $(GCC) \
        -m$(BITS) \
        -fPIC \
        -DQUESTA \
        -g \
        -W \
        -shared \
        -x c \
        -I$(MTI_HOME)/include \
        $(DPI_SRC) \
        -o $(LIBDIR)/$(LIBNAME).so

GCC_WINCMD = \
        $(WIN_GCC) \
        -g \
        -DQUESTA \
        -W \
        -shared \
        -Bsymbolic \
        -x c \
        -I$(MTI_HOME)/include \
        $(DPI_SRC) \
        -o $(LIBDIR)/$(LIBNAME).dll \
        $(MTI_HOME)/win32/mtipli.dll -lregex

WIN_GCC = $(MTI_HOME)/gcc-4.2.1-mingw32vc9/bin/g++.exe

VLIB =  vlib work

VLOG =  vlog \
        -timescale "1ns/1ns" \
        $(DPILIB_VLOG_OPT) \
        $(VLOG_OPT) \
        $(OPT_C) \
        -mfcu \
        -suppress 2181 \
        +acc=rmb \
        -writetoplevels questa.tops \
        +incdir+$(UVM_HOME)/src \
        $(UVM_HOME)/src/uvm.sv


VSIM =  vsim \
        $(DPILIB_VSIM_OPT) \
        $(VSIM_OPT) \
        $(OPT_R) \
        -c \
        -do "run -all; q" \
        -l questa.log \
        -f questa.tops

N_ERRS = 0
N_FATALS = 0

CHECK = \
    @$(TEST) \( `grep -c 'UVM_ERROR :    $(N_ERRS)' questa.log` -eq 1 \) -a \
         \( `grep -c 'UVM_FATAL :    $(N_FATALS)' questa.log` -eq 1 \)

#---------------------------------------------------------------
# If USES_DPI is set, enables compilation and loading of DPI
# libraries. Enabling DPI adds +acc on command line, which
# may adversely affect simulator performance.
#---------------------------------------------------------------

ifeq ($(USES_DPI),1)
  DPILIB_VLOG_OPT = 
  DPILIB_VSIM_OPT = -sv_lib $(LIBDIR)/uvm_dpi 
  DPILIB_TARGET = dpi_lib$(BITS)
else
  DPILIB_VLOG_OPT = +define+UVM_NO_DPI 
  DPILIB_VSIM_OPT = 
  DPILIB_TARGET =
endif


prepare: clean vlib $(DPILIB_TARGET)


dpi_lib:
	mkdir -p $(LIBDIR)
	$(GCCCMD)

dpi_libWin:
	mkdir -p $(LIBDIR)
	$(GCC_WINCMD)

dpi_lib32:
	make -f Makefile.questa BITS=32 dpi_lib

dpi_lib64:
	make -f Makefile.questa LIBNAME=uvm_dpi BITS=64 dpi_lib

vlib: $(DPILIB_TARGET)
	vlib work

clean:
	rm -rf *~ work vsim.wlf* *.log questa.tops transcript *.vstf


